name: health_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.2.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  cloud_firestore: ^4.15.8
  barcode_scan2: ^4.3.0
  http: ^1.2.0
  flutter_gemini: ^2.0.3

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

